---
abstract: 'CPAN Testers report object'
author:
  - '=over '
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.26
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::Testers::Report
name: CPAN-Testers-Report
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Metabase::Fact::Hash: 0
  Metabase::Report: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
