--- #YAML:1.0
name:                CPAN-Testers-Report
version:             0.03
abstract:            Creates CPAN Testers test-report objects
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Config:                        0
    Time::Local:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam J. Foxson <afoxson@pobox.com>
